### PR TITLE
Really Basic UI, just a window and a menu and a model

### PR DESCRIPTION
**Pull request by ChadNedzlek**

### CODE REVIEW

**Comment by adiaaida** [comment]
Is this intentional:

Screen Shot 2020-08-06 at 7 19 52 AM

(The underscores in the File menu?)

**Comment by adiaaida** [comment]
We should rename the sln file if possible.

**Comment by ChadNedzlek** [comment]
The underscores show up on the Mac?  That's... annoying.  It shouldn't do that.  It's the way you declare the Alt accelerators for the menu.  If that's what it does on OSX then we'll need different menu generation code for each OS.

**Comment by ChadNedzlek** [comment]
I've got a better one!

**Pull request closed without merging**
